# K8s for calculator app / image
apiVersion: apps/v1
kind: Deployement
metadata:
  name: calc-deployement
spec:
  selector:
    matchLabels:
      app: calc
  replicas: 2 
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: praveen0635/project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

